# http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_basic_environment.html#basics-packages
- name: Install rabbitmq server
  apt: name=rabbitmq-server state=latest

- name: Create openstack rabbitmq user
  rabbitmq_user:
    user={{ rabbitmq_user }}
    password={{ rabbitmq_password }}
    vhost=/
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present
  notify: restart rabbitmq-server
