- hosts: compute-controller
  remote_user: sistemas
  sudo: yes
  roles:
  - ubuntu-cloud
  - ntp
  - compute-controller

- hosts: compute-hypervisor
  remote_user: sistemas
  sudo: yes
  roles:
  - ubuntu-cloud
  - ntp
  - compute-hypervisor
