# Databases services
- hosts: databases
  roles:
  - ubuntu-cloud
  - ntp
  - mysql
  - rabbitmq

# Keystone service
- hosts: keystone
  roles:
  - ubuntu-cloud
  - ntp
  - keystone

# Image service
- hosts: glance
  roles:
  - ubuntu-cloud
  - ntp
  - glance

# Networking and compute services
- hosts: networking-compute-controller
  roles:
  - ubuntu-cloud
  - ntp
  - networking-compute-controller

# Dashboard service
- hosts: dashboard
  roles:
#  - ubuntu-cloud
#  - ntp
  - dashboard

# Block Storage service
- hosts: cinder
  roles:
#  - ubuntu-cloud
#  - ntp
  - cinder

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - ubuntu-cloud
  - ntp
  - kvm-hypervisor
  tags: workingon

# Adding hypervisors
- hosts: lxc-hypervisor
  roles:
  - ubuntu-cloud
  - ntp
  - lxc-hypervisor
