# Databases services
- hosts: databases
  roles:
  - openstack-repositories
  - ntp
  - sql-database
  - message-queue
  tags:
  - databases
  - sql-database
  - postgresql
  - mysql
  - message-queue
  - rabbitmq

# Keystone service
- hosts: identity
  roles:
  - openstack-repositories
  - ntp
  - identity
  tags:
  - identity
  - keystone

# Image service
- hosts: image
  roles:
  - openstack-repositories
  - ntp
  - image
  tags:
  - image
  - glance

# Networking and compute services
- hosts: networking-compute-controller
  roles:
  - openstack-repositories
  - ntp
  - networking-compute-controller
  tags:
  - networking-compute-controller
  - controller
  - networking

# Dashboard service
- hosts: dashboard
  roles:
  - openstack-repositories
#  - ntp
  - dashboard
  tags:
  - dashboard
  - horizon

# Block Storage service
- hosts: block-storage
  roles:
  - openstack-repositories
#  - ntp
  - block-storage
  tags:
  - cinder
  - block-storage

# Ochestration service
- hosts: orchestation
  roles:
#  - openstack-repositories
#  - ntp
  - orchestation
  tags:
  - heat
  - orchestation
  - cloudformation

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - openstack-repositories
  - ntp
  - kvm-hypervisor
  tags:
  - kvm-hypervisor
  - compute

- hosts: lxd-hypervisor
  roles:
  - openstack-repositories
  - ntp
  - lxd-hypervisor
  tags:
  - lxd-hypervisor
  - compute
