- hosts: databases
  roles:
  - ubuntu-cloud
  - ntp
  - mysql
  - rabbitmq
  tags: workingon

- hosts: keystone
  roles:
  - ubuntu-cloud
  - ntp
  - keystone
  tags: workingon

- hosts: glance
  roles:
  - ubuntu-cloud
  - ntp
  - glance
  tags: workingon

- hosts: networking-compute-controller
  roles:
  - ubuntu-cloud
  - ntp
  - networking-compute-controller
  tags: workingon

- hosts: dashboard
  roles:
  - ubuntu-cloud
  - ntp
  - dashboard
  tags: workingon

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - ubuntu-cloud
  - ntp
  - kvm-hypervisor
