- hosts: databases
  roles:
  - ubuntu-cloud
  - ntp
  - mysql
  - rabbitmq

- hosts: keystone
  roles:
  - ubuntu-cloud
  - ntp
  - keystone

- hosts: glance
  roles:
  - ubuntu-cloud
  - ntp
  - glance

- hosts: networking-compute-controller
  roles:
  - ubuntu-cloud
  - ntp
  - networking-compute-controller

- hosts: dashboard
  roles:
  - ubuntu-cloud
  - ntp
  - dashboard

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - ubuntu-cloud
  - ntp
  - kvm-hypervisor
