- hosts: databases
  remote_user: sistemas
  sudo: yes
  roles:
  - ubuntu-cloud
  - ntp
  - mysql
  - rabbitmq

- hosts: keystone
  remote_user: sistemas
  sudo: yes
  roles:
  - ubuntu-cloud
  - ntp
  - keystone

- hosts: glance
  remote_user: sistemas
  sudo: yes
  roles:
  - ubuntu-cloud
  - ntp
  - glance

- include: compute.yml

- include: networking.yml

- include: dashboard.yml
