# Databases services
- hosts: databases
  roles:
  - ubuntu-cloud
  - ntp
  - mysql
  - rabbitmq
  tags: workingon

# Keystone service
- hosts: keystone
  roles:
#  - ubuntu-cloud
#  - ntp
  - keystone
  tags: workingon

# Image service
- hosts: glance
  roles:
#  - ubuntu-cloud
#  - ntp
  - glance
  tags: workingon

# Networking and compute services
- hosts: networking-compute-controller
  roles:
#  - ubuntu-cloud
#  - ntp
  - networking-compute-controller
  tags: workingon

# Dashboard service
- hosts: dashboard
  roles:
#  - ubuntu-cloud
#  - ntp
  - dashboard
  tags: workingon

# Block Storage service
- hosts: cinder
  roles:
#  - ubuntu-cloud
#  - ntp
  - cinder
  tags: workingon

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - ubuntu-cloud
  - ntp
  - kvm-hypervisor
