#
# Database services
- hosts: databases
  roles:
  - ntp
  - sql-database
  - message-queue
  - memcached
  tags:
  - databases
  - sql-database
  - postgresql
  - mysql
  - message-queue
  - rabbitmq
  - memcached

# Keystone service
- hosts: identity
  roles:
  - ntp
  - identity
  environment:
    OS_TOKEN: "{{ administration_token }}"
    OS_URL: "http://{{ admin_hostname }}:35357/v3"
    OS_IDENTITY_API_VERSION: 3
  tags:
  - identity
  - keystone

# Image service
- hosts: image
  roles:
  - ntp
  - image
  environment:
    OS_TOKEN: "{{ administration_token }}"
    OS_URL: "http://{{ admin_hostname }}:35357/v3"
    OS_IDENTITY_API_VERSION: 3
  tags:
  - image
  - glance

# Networking and compute services
- hosts: networking-compute-controller
  roles:
  - ntp
  - networking-compute-controller
  environment:
    OS_TOKEN: "{{ administration_token }}"
    OS_URL: "http://{{ admin_hostname }}:35357/v3"
    OS_IDENTITY_API_VERSION: 3
  tags:
  - networking-compute-controller
  - controller
  - networking

# Dashboard service
- hosts: dashboard
  roles:
#  - ntp
  - dashboard
  tags:
  - dashboard
  - horizon

# Block Storage service
- hosts: block-storage
  roles:
#  - ntp
  - block-storage
  tags:
  - cinder
  - block-storage

# Ochestration service
- hosts: orchestation
  roles:
#  - ntp
  - orchestation
  tags:
  - heat
  - orchestation
  - cloudformation

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - ntp
  - kvm-hypervisor
  tags:
  - kvm-hypervisor
  - compute

- hosts: lxd-hypervisor
  roles:
  - ntp
  - lxd-hypervisor
  tags:
  - lxd-hypervisor
  - compute
