# Databases services
- hosts: databases
  roles:
  - openstack-repositories
  - ntp
  - mysql
  - rabbitmq

# Keystone service
- hosts: keystone
  roles:
  - openstack-repositories
  - ntp
  - keystone

# Image service
- hosts: glance
  roles:
  - openstack-repositories
  - ntp
  - glance

# Networking and compute services
- hosts: networking-compute-controller
  roles:
  - openstack-repositories
  - ntp
  - networking-compute-controller

# Dashboard service
- hosts: dashboard
  roles:
  - openstack-repositories
#  - ntp
  - dashboard

# Block Storage service
- hosts: cinder
  roles:
  - openstack-repositories
#  - ntp
  - cinder

# Ochestration service
- hosts: heat
  roles:
#  - openstack-repositories
#  - ntp
  - heat

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - openstack-repositories
  - ntp
  - kvm-hypervisor
  tags: workingon

# Adding hypervisors
#- hosts: lxc-hypervisor
#  roles:
#  - openstack-repositories
#  - ntp
#  - lxc-hypervisor
