- hosts: databases
  roles:
  - ubuntu-cloud
  - ntp
  - mysql
  - rabbitmq
  tags:
  - workingon

- hosts: keystone
  roles:
  - ubuntu-cloud
  - ntp
  - keystone
  tags:
  - workingon

- hosts: glance
  roles:
  - ubuntu-cloud
  - ntp
  - glance
  tags:
  - workingon

- include: compute.yml

- include: networking.yml

- include: dashboard.yml
