- hosts: databases
  remote_user: root
  roles:
  - ubuntu-cloud
  - ntp
  - mysql
  - rabbitmq

- hosts: keystone
  remote_user: root
  roles:
  - ubuntu-cloud
  - ntp
  - keystone

- hosts: glance
  remote_user: root
  roles:
  - ubuntu-cloud
  - ntp
  - glance

- hosts: compute-controller
  remote_user: root
  roles:
  - ubuntu-cloud
  - ntp
  - compute-controller

- hosts: compute-hypervisor
  remote_user: root
  roles:
  - ubuntu-cloud
  - ntp
  - compute-hypervisor

- include: networking
