# Databases services
- hosts: databases
  roles:
  - openstack-repositories
  - ntp
  - sql-database
  - message-queue

# Keystone service
- hosts: identity
  roles:
  - openstack-repositories
  - ntp
  - identity

# Image service
- hosts: image
  roles:
  - openstack-repositories
  - ntp
  - image

# Networking and compute services
- hosts: networking-compute-controller
  roles:
  - openstack-repositories
  - ntp
  - networking-compute-controller

# Dashboard service
- hosts: dashboard
  roles:
  - openstack-repositories
#  - ntp
  - dashboard

# Block Storage service
- hosts: block-storage
  roles:
  - openstack-repositories
#  - ntp
  - block-storage

# Ochestration service
- hosts: heat
  roles:
#  - openstack-repositories
#  - ntp
  - heat
  tags: workingon

# Adding hypervisors
- hosts: kvm-hypervisor
  roles:
  - openstack-repositories
  - ntp
  - kvm-hypervisor
  tags: workingon

# Adding hypervisors
#- hosts: lxc-hypervisor
#  roles:
#  - openstack-repositories
#  - ntp
#  - lxc-hypervisor
