# http://docs.openstack.org/liberty/install-guide-ubuntu/keystone.html
# http://docs.openstack.org/liberty/install-guide-ubuntu/keystone-install.html
# mysql
- name: Create mysql database
  mysql_db: name=keystone state=present
  when: relational_database == "mysql"

- name: Create mysql database user to localhost
  mysql_user: name=keystone host=localhost password={{ keystone_dbpass }} priv=keystone.*:ALL,GRANT state=present
  when: relational_database == "mysql"

- name: Create mysql database user to %
  mysql_user: name=keystone host=% password={{ keystone_dbpass }} priv=keystone.*:ALL,GRANT state=present
  when: relational_database == "mysql"

# postgresql
- name: Create postgresql database
  postgresql_db: name=keystone
  when: relational_database == "postgresql"

- name: Create postgresql database user
  postgresql_user: db=keystone name=keystone password={{ keystone_dbpass }} priv=ALL
  when: relational_database == "postgresql"


- name: Disable keystone service autostart
  template: src=keystone.override.j2 dest=/etc/init/keystone.override
  tags:
  - appliance

- name: Install keystone
  apt: name={{ item }} state=present
  with_items:
  - keystone
  - apache2
  - libapache2-mod-wsgi
  - memcached
  - python-memcache
  tags:
  - appliance

- name: Configure keystone service
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf owner=keystone group=root
  notify:
  - populate database

- meta: flush_handlers

- name: Configure apache hostname
  lineinfile: dest=/etc/apache2/apache2.conf regexp='^\s*ServerName' line="ServerName {{ admin_hostname }}" owner=root group=root mode=0644
  notify:
  - restart apache2

- name: Configure apache virtualhost
  template: src=wsgi-keystone.conf.j2 dest=/etc/apache2/sites-available/wsgi-keystone.conf owner=root group=root mode=0644
  notify:
  - restart apache2

- name: Enable apache virtualhost
  file: src=/etc/apache2/sites-available/wsgi-keystone.conf dest=/etc/apache2/sites-enabled/wsgi-keystone.conf owner=root group=root state=link
  notify:
  - restart apache2

- meta: flush_handlers

- name: Remove sqlite database
  file: path=/var/lib/keystone/keystone.db state=absent

# Create the service entity and API endpoint
# http://docs.openstack.org/liberty/install-guide-ubuntu/keystone-services.html
- name: Test if service entity exists
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack service list | grep " identity "| wc -l
  register: service_entity_exists
  ignore_errors: True
  failed_when: "'0' in service_entity_exists.stdout"

- name: Create the service entity for the Identity service
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack service create --name {{ keystone_keystone_name }} --description "OpenStack Identity" identity
  when: service_entity_exists|failed

- name: Test if endpoints exists
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack endpoint list | grep " identity " | wc -l
  register: endpoint_exists
  ignore_errors: True
  failed_when: "'0' in endpoint_exists.stdout"

- name: Create the Identity service API endpoints
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack endpoint create --region {{ region_name }} identity public http://{{ admin_hostname }}:5000/v2.0
    openstack endpoint create --region {{ region_name }} identity internal http://{{ admin_hostname }}:5000/v2.0
    openstack endpoint create --region {{ region_name }} identity admin http://{{ admin_hostname }}:5000/v2.0
  when: endpoint_exists|failed


# Create projects, users and roles
# http://docs.openstack.org/liberty/install-guide-ubuntu/keystone-users.html
- name: Test if admin project exists
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack project list | grep " {{ keystone_admin_project_name }} " | wc -l
  register: exists
  ignore_errors: True
  failed_when: "'0' in exists.stdout"

- name: Create the admin project
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack project create --domain {{ keystone_default_domain_name }} --description "{{ keystone_admin_project_description }}" {{ keystone_admin_project_name }}
  when: exists|failed


- name: Test if admin user exists
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack user list | grep " {{ keystone_admin_name }} " | wc -l
  register: exists
  ignore_errors: True
  failed_when: "'0' in exists.stdout"

- name: Create the admin user, role and asociate both to admin project
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack user create --domain {{ keystone_default_domain_name }} --password {{ keystone_admin_password }} {{ keystone_admin_name }}
    openstack role create {{ keystone_admin_role }}
    openstack role add --project {{ keystone_admin_project_name }} --user {{ keystone_admin_name }} {{ keystone_admin_role }}
  when: exists|failed


# Create the service project
- name: Test if service project exists
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack project list | grep " service " | wc -l
  register: exists
  ignore_errors: True
  failed_when: "'0' in exists.stdout"

- name: Create the service project
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack project create --domain {{ keystone_default_domain_name }} --description "{{ keystone_service_project_description}}" {{ keystone_service_project_name }}
    openstack role create {{ keystone_admin_role }}
    openstack role add --project {{ keystone_admin_project_name }} --user {{ keystone_admin_name }} {{ keystone_admin_role }}
  when: exists|failed


# Non admin project, user and role
- name: Test if non admin project exists
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack project list | grep " {{ keystone_user_project_name }} " | wc -l
  register: exists
  ignore_errors: True
  failed_when: "'0' in exists.stdout"

- name: Create the non admin project
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack project create --domain {{ keystone_default_domain_name }} --description "{{ keystone_user_project_description }}" {{ keystone_user_project_name }}
  when: exists|failed


- name: Test if non admin user exists
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack user list | grep " {{ keystone_user_name }} " | wc -l
  register: exists
  ignore_errors: True
  failed_when: "'0' in exists.stdout"

- name: Create the admin user, role and associate both to admin project
  shell: |
    export OS_TOKEN={{ administration_token }}
    export OS_URL=http://{{ admin_hostname }}:35357/v3
    export OS_IDENTITY_API_VERSION=3
    openstack user create --domain {{ keystone_default_domain_name }} --password {{ keystone_user_password }} {{ keystone_user_name }}
    openstack role create {{ keystone_user_role }}
    openstack role add --project {{ keystone_user_project_name }} --user {{ keystone_user_name }} {{ keystone_user_role }}
  when: exists|failed


# http://docs.openstack.org/liberty/install-guide-ubuntu/keystone-openrc.html
#  Create OpenStack client environment scripts
- name: Create admin-openrc.sh environment script
  template: src=admin-openrc.sh.j2 dest=/root/{{ keystone_admin_name }}-openrc.sh

- name: Create {{ keystone_user_name }} environment script
  template: src=user-openrc.sh.j2 dest=/root/{{ keystone_user_name }}-openrc.sh
