controller_hostname: os-vcenter-01.paradigmatecnologico.com
rabbitmq_guest_password: RABBIT_PASS
#TODO: mysql_root_password: MYSQL_ROOT_PASS
# keystone section vars: http://docs.openstack.org/juno/install-guide/install/apt/content/ch_keystone.html
keystone_dbpass: KEYSTONE_DBPASS
administration_token: 4f8df8a0581622075047
keystone_admin_name: admin
keystone_admin_password: admin
keystone_admin_email: admin@localhost
keystone_admin_tenant_name: admin
keystone_admin_tenant_description: Admin Tenant
keystone_admin_role: admin
keystone_user_name: demo
keystone_user_password: demo
keystone_user_email: demo@localhost
keystone_user_tenant_name: demo
keystone_user_tenant_description: Demo Tenant
keystone_service_tenant_name: service
keystone_service_tenant_description: service
# --publicurl http://controller:5000/v2.0
public_hostname: os-vcenter-01.paradigmatecnologico.com
# --internalurl http://controller:5000/v2.0
internal_hostname: os-vcenter-01.paradigmatecnologico.com
# --adminurl http://controller:35357/v2.0
admin_hostname: os-vcenter-01.paradigmatecnologico.com
region_name: RegionOne

# Glance vars
# http://docs.openstack.org/juno/install-guide/install/apt/content/ch_glance.html
glance_dbpass: GLANCE_DBPASS
keystone_glance_name: glance
keystone_glance_password: glance
# Nova vars
# http://docs.openstack.org/juno/install-guide/install/apt/content/ch_nova.html
nova_dbpass: NOVA_DBPASS
keystone_nova_name: nova
keystone_nova_password: nova
# Neutron vars
# http://docs.openstack.org/juno/install-guide/install/apt/content/neutron-controller-node.html
neutron_dbpass: NEUTRON_DBPASS
keystone_neutron_name: neutron
keystone_neutron_password: neutron
# http://docs.openstack.org/juno/install-guide/install/apt/content/neutron-network-node.html
metadata_secret: METADATA_SECRET
