# http://docs.openstack.org/kilo/install-guide/install/apt/content/ch_basic_environment.html#basics-packages
# Ubuntu 14.04
- name: Install ubuntu cloud keyring
  apt: name=ubuntu-cloud-keyring state=latest
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

- name: Add apt_repository dependency
  apt: name=python-pycurl state=latest
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

- name: Add ubuntu cloud repository
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/kilo main' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

- name: Upgrade distribution
  apt: upgrade=dist
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

# Debian 8
# Use Mirantis repositories
- name: Install gpg key
  shell: wget -qO - http://icehouse.dev-debian.pkgs.enovance.com/debian/dists/icehouse/pubkey.gpg | sudo apt-key add -
  when: ansible_distribution == "Debian" and ansible_distribution_version | search("^8")

- name: Add openstack backports
  apt_repository: repo='deb http://kilo-jessie.pkgs.mirantis.com/debian jessie-kilo-backports main' state=present update_cache=yes
  when: ansible_distribution == "Debian" and ansible_distribution_version | search("^8")

- name: Add openstack backports nochange
  apt_repository: repo='deb http://kilo-jessie.pkgs.mirantis.com/debian jessie-kilo-backports-nochange main' state=present update_cache=yes
  when: ansible_distribution == "Debian" and ansible_distribution_version | search("^8")

# http://docs.openstack.org/kilo/install-guide/install/yum/content/ch_basic_environment.html
# CentOS 7
- name: Enable epel repository
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_version | search("^7")

- name: Enable kilo repository
  yum: name=http://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_version | search("^7")

- name: Upgrade distribucion
  yum: name=* state=latest
  when: ansible_distribution == "CentOS" and ansible_distribution_version | search("^7")

- name: Manage SELinux policies for OpenStack services
  yum: name=openstack-selinux state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_version | search("^7")
