- name: populate database
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder

- name: restart cinder-api
  service: name=cinder-api state=restarted

- name: restart cinder-scheduler
  service: name=cinder-scheduler state=restarted
