# http://docs.openstack.org/juno/install-guide/install/apt/content/section_neutron-networking.html
# http://docs.openstack.org/juno/install-guide/install/apt/content/neutron-network-node.html

- name: Enable ip forwarding
  sysctl: name=net.ipv4.ip_forward value=1 reload=yes sysctl_set=yes

- name: Disable all rp_filter
  sysctl: name=net.ipv4.conf.all.rp_filter value=0 reload=yes sysctl_set=yes

- name: Disable default rp_filter
  sysctl: name=net.ipv4.conf.default.rp_filter value=0 reload=yes sysctl_set=yes

- name: Install networking components
  apt: name={{ item }} state=present
  with_items:
  - neutron-plugin-ml2
  - neutron-plugin-openvswitch-agent
  - neutron-l3-agent
  - neutron-dhcp-agent

- name: Register tenant_id var to use in /etc/neutron/neutron.conf
  shell: |
    export OS_SERVICE_TOKEN={{ administration_token }}
    export OS_SERVICE_ENDPOINT=http://{{ admin_hostname }}:35357/v2.0
    keystone tenant-get service | grep id | awk '{print $4}'
  register: tenant_id

- name: Configure neutron server component
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf owner=root group=neutron mode=0644
  notify:
  - restart neutron-plugin-openvswitch-agent
  - restart neutron-l3-agent
  - restart neutron-dhcp-agent
  - restart neutron-metadata-agent

- name: Configure Modular Layer 2 (ML2) plug-in
  template: src=ml2_conf.ini.j2 dest=/etc/neutron/plugins/ml2/ml2_conf.ini owner=root group=neutron mode=0644
  notify:
  - restart neutron-plugin-openvswitch-agent

- name: Configure Layer-3 (L3) agent
  template: src=l3_agent.ini.j2 dest=/etc/neutron/l3_agent.ini owner=root group=neutron mode=0644
  notify:
  - restart neutron-l3-agent

- name: Configure the DHCP agent
  template: src=dhcp_agent.ini.j2 dest=/etc/neutron/dhcp_agent.ini owner=root group=root mode=0644
  notify:
  - restart neutron-dhcp-agent

- name: Configure the metadata agent
  template: src=metadata_agent.ini.j2 dest=/etc/neutron/metadata_agent.ini owner=root group=root mode=0644
  notify:
  - restart neutron-metadata-agent

# Configure Open vSwitch service
- name: Restart OVS service
  shell: service openvswitch-switch restart; ethtool -K eth1 gro off

- name: Add the external bridge
  openvswitch_bridge: bridge=br-ex state=present

- name: Add a port to the external bridge that connects to the physical external network interface
  openvswitch_port: bridge=br-ex port=eth1 state=present
