# http://docs.openstack.org/liberty/install-guide-ubuntu/environment-sql-database.html
- name: Install memcached server
  apt: name={{ item }} state=present
  with_items:
    - memcached
    - python-memcache
  tags:
  - appliance

- name: Configure memcached server
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify: restart memcached
