# http://docs.openstack.org/juno/install-guide/install/apt/content/ch_basic_environment.html#basics-packages
- name: Install ubuntu cloud keyring
  apt: name=ubuntu-cloud-keyring state=latest

- name: Add apt_repository dependency
  apt: name=python-pycurl state=latest

- name: Add ubuntu cloud repository
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/kilo main' state=present update_cache=yes

- name: Upgrade distribution
  apt: upgrade=dist
